version: '3'

services:
  frontend:
    build:
      context: ./client
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./server
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
