# Utiliza una imagen base de PostgreSQL
FROM postgres:latest

# Variables de entorno para configurar la base de datos (cambia los valores según tu configuración)
ENV POSTGRES_DB mydb
ENV POSTGRES_USER myuser
ENV POSTGRES_PASSWORD mypassword

# Expone el puerto en el que la base de datos estará escuchando (opcional)
EXPOSE 5432
